### ISSUE TITLE
Install Linux Wails deps步骤错误

### ISSUE THREAD

**Issue by jianggujin** [dAppCore/build#30]
```yml
- name: Install Linux Wails deps
      if: inputs.build == 'true' && runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
      shell: bash
```
构建出现错误
Reading package lists... 
232Reading package lists... 
233Building dependency tree... 
234Reading state information... 
235E: Unable to locate package libwebkit2gtk-4.0-dev 
236E: Couldn't find any package by glob 'libwebkit2gtk-4.0-dev' 
237E: Couldn't find any package by regex 'libwebkit2gtk-4.0-dev' 
238Error: Process completed with exit code 100.
